### ISSUE TITLE
Lava Installation failed

### ISSUE THREAD

**Issue by Rashedape** [lava-nc/lava#251] opened 2022-05-20 20:07 UTC
### Discussed in https://github.com/lava-nc/lava/discussions/250

<div type='discussions-op-text'>

<sup>Originally posted by **Rashedape** May 16, 2022</sup>
Hello,
I am trying to install Lava on my INRC cloud account and I am following the Lava (https://lava-nc.org/) suggested poerty-based approach. Unfortunately, I am not able to complete the installation process. After the poetry installation command, I am getting the following error:
 • Updating scipy (1.7.3 -> 1.8.0): Failed
  EnvCommandError
..........(some warning message)
        Successfully uninstalled scipy-1.7.3
  ERROR: Could not install packages due to an OSError: [Errno 16] Device or resource busy: '.nfs0000000007045c6f0000016b'

</div>

**Comment by mgkwill** [comment] 2022-06-09 19:22
Hi @Rashedape.

This is an issue with the nfs share. 

Something is still holding an open lock on the file path that is being used to install scipy-1.7.3.

I suggest in these cases to look for all open python processes that could be holding open the file path 
`ps -ef | grep <user-name> | grep python`
and kill that process
`kill -9 <process id>`

This should allow you to install. Though this is neither a lava issue or poetry issue but one caused by  the NFS share upon which the install is happening and the fact that some program is keeping it busy.

**Comment by tim-shea** [comment] 2022-07-21 17:41
Seems resolved. Closing.

**Closed by tim-shea** 2022-07-21 17:41 UTC
Labels: bug

**Comment by mgkwill** [comment] 2022-10-11 09:16
This is generally an issue with NFS where a file handle is still open. Try
‘’’ ps -ef | grep <program that would use open file> ‘’’ then kill that
instance and try again.

Thanks,
Marcus
