### ISSUE TITLE
Runtime throws an error when a pause request is sent after "done" message

### ISSUE THREAD

**Issue by AlessandroPierro** [lava-nc/lava#513] opened 2022-12-02 12:30 UTC
### User story

As a user I do not expect a runtime error, when requesting pause - even if the process has already reached the last time step.

### Conditions of satisfaction
- A pause request does not raise an error, even if the process cannot be paused anymore, since it already reached the last time step.
- If a pause request is received, when the process is already finished - it should give a meaningful warning or a meaningful error message (TBD).

### Acceptance tests
- Test requesting a pause from the runtime for a process running only 1 time step in non-blocking mode (maybe delay the pause request, to really make sure the process execution has finished)
- Requesting pause in the management phase of the last time step.

**Comment by PhilippPlank** [comment] 2022-12-05 11:01
In ln 350 ff in runtime.py

`            for recv_port in self.service_to_runtime:
                data = recv_port.recv()
                if not enum_equal(data, MGMT_RESPONSE.PAUSED):
                    if enum_equal(data, MGMT_RESPONSE.ERROR):
                        # Receive all errors from the ProcessModels
                        error_cnt = 0
                        for actors in \
                                self._messaging_infrastructure.actors:
                            actors.join()
                            if actors.exception:
                                _, traceback = actors.exception
                                self.log.info(traceback)
                                error_cnt += 1
                        self.stop()
                        raise RuntimeError(
                            f"{error_cnt} Exception(s) occurred. See "
                            f"output above for details.")
                    else:
                        if recv_port.probe():
                            data = recv_port.recv()
                        if not enum_equal(data, MGMT_RESPONSE.PAUSED):
                            raise RuntimeError(
                                f"{data} Got Wrong Response for Pause.")`

Could we also check if the received command is the Done token and if yes, instead of raising a runtime error, just give a warning that the pause request was rejected, because the execution had already finished?

Also asking @awintel here, what the expected behavior should be if a pause request was given by the user, but the execution finished before the pause request reached the compute resource.

**Comment by joyeshmishra** [comment] 2023-02-21 23:09
@AlessandroPierro - It would be great if you could provide us with a test for this. @ysingh7 will try writing but it will be useful if we can replicate the exact behavior which caused the problem.

**Comment by joyeshmishra** [comment] 2023-03-07 18:45
PR was merged. Closing.

**Closed by joyeshmishra** 2023-03-07 18:45 UTC
Labels: 1-bug, area: magma/runtime
