### ISSUE TITLE
StateProbe doesn't work for variables aliased by a SubProcessModel

### ISSUE THREAD

**Issue by Gavinator98** [lava-nc/lava#548] opened 2022-12-31 00:54 UTC
Objective of issue:
StateProbes currently don't work for variables aliased by SubProcessModels. 

**Lava version:**

- [x] **0.6.0** (feature release)

**I'm submitting a ...** 

- [x] bug report
- [ ] feature request
- [ ] documentation request

**Current behavior:**

- loihi2_state_probes.py raises the following exception (nxsdk_runtime_service.py catches this exception, but doesn't print a stack trace):
```
Traceback (most recent call last):
  File "~/lava/lava_nx_env/lib/python3.8/site-packages/lava/magma/runtime/runtime_services/nxsdk_runtime_service.py", line 272, in run
    self.pre_run_callback_fx()
  File "~/lava/lava_nx_env/lib/python3.8/site-packages/lava/magma/runtime/runtime_services/nxsdk_runtime_service.py", line 551, in pre_run_callback_fx
    cfx.pre_run_callback(
  File "~/lava/lava_nx_env/lib/python3.8/site-packages/lava/utils/loihi2_state_probes.py", line 85, in pre_run_callback
    var_model = var_id_to_model_map[self.var.id]
KeyError: 6
```
- The runtime doesn't appear to start
- Reading the StateProbe time_series causes the following exception:
```
  File "~/lava/src/broken.py", line 42, in <module>
    print(probe_v.time_series)
  File "~/lava/lava_nx_env/lib/python3.8/site-packages/lava/utils/loihi2_state_probes.py", line 65, in time_series    return self._get_data()
  File "~/lava/lava_nx_env/lib/python3.8/site-packages/lava/utils/loihi2_state_probes.py", line 144, in _get_data
    probe_data = np.load(self._temp_dir + f"var_id_{self.var.id}.npy",
  File "~/lava/lava_nx_env/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: ~/lava/lava_nx_env/lib/python3.8/site-packages/lava/utils/temp_state/var_id_0.npy'
```
**Expected behavior:**

- StateProbe monitors the variable.

**Steps to reproduce:**

- Attack a StateProbe to the voltage variable of an ExampleProcess as described below.
- Run for any number of timesteps

**Related code:**

```
class ExampleProcess(AbstractProcess):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.voltage = Var(shape=(1,))

@implements(proc=ExampleProcess, protocol=LoihiProtocol)
@requires(Loihi2NeuroCore)
class ExampleProcessModel(AbstractSubProcessModel):
    def __init__(self, proc: AbstractProcess):
        self.neuron = LIF(shape=(1,),
                          du=0,
                          dv=0,
                          vth=1000,
                          bias_mant=100,
                          bias_exp=4)
        proc.vars.voltage.alias(self.neuron.v)
```

**Comment by PhilippPlank** [comment] 2023-01-09 16:59
Thank you for reporting this issue. We are working on a fix for this bug.

**Comment by PhilippPlank** [comment] 2023-01-11 19:03
The issue is fixed and should work with the next release of the loihi extension for lava (or if you install from code).

**Closed by PhilippPlank** 2023-01-11 19:03 UTC
Labels: 1-bug, 0-needs-review
