### ISSUE TITLE
OutPort reshape/flatten has compilation issue

### ISSUE THREAD

**Issue by bamsumit** [lava-nc/lava#163] opened 2022-01-20 17:12 UTC
Objective of issue:

**Lava version:**
- [ ] **0.3.0** (feature release)
- [ ] **0.2.1** (bug fixes)
- [x] **0.2.0** (current version)
- [ ] **0.1.2**

**I'm submitting a ...** 

- [x] bug report
- [ ] feature request
- [ ] documentation request

**Current behavior:**

- The compilation fails when `flatten()` is used.

**Expected behavior:**

- It should run.

**Steps to reproduce:**

- Code is below

**Related code:**

```python
from typing import List
import numpy as np

from lava.magma.core.run_configs import RunConfig
from lava.magma.core.run_conditions import RunSteps
from lava.proc.io.source import RingBuffer as SendProcess
from lava.proc.io.sink import RingBuffer as ReceiveProcess
from lava.magma.core.model.py.model import PyLoihiProcessModel


class TestRunConfig(RunConfig):
    """Run configuration selects appropriate ProcessModel based on tag
    """
    def __init__(self, select_tag: str = 'fixed_pt'):
        super(TestRunConfig, self).__init__(custom_sync_domains=None)
        self.select_tag = select_tag

    def select(
        self, _, proc_models: List[PyLoihiProcessModel]
    ) -> PyLoihiProcessModel:
        for pm in proc_models:
            if self.select_tag in pm.tags:
                return pm
        raise AssertionError('No legal ProcessModel found.')


if __name__ == '__main__':
    num_steps = 10
    shape = (64, 32, 16)
    input = np.random.randint(256, size=shape + (num_steps,))
    input -= 128

    source = SendProcess(data=input)
    sink = ReceiveProcess(shape=(np.prod(shape), ), buffer=num_steps)
    source.out_ports.s_out.flatten().connect(sink.in_ports.a_in)

    run_condition = RunSteps(num_steps=num_steps)
    run_config = TestRunConfig(select_tag='floating_pt')
    sink.run(condition=run_condition, run_cfg=run_config)
    output = sink.data.get()
    sink.stop()

    expected = input.reshape([-1, num_steps])
    print(np.all(output == expected))

```

**Other information:**

**Line numbers may be different. I had some local changes.**
```
Traceback (most recent call last):
  File "test_permute.py", line 82, in <module>
    sink.run(condition=run_condition, run_cfg=run_config)
  File "/home/sshresth/lava-nc/lava/src/lava/magma/core/process/process.py", line 396, in run
    executable = self.compile(run_cfg)
  File "/home/sshresth/lava-nc/lava/src/lava/magma/core/process/process.py", line 345, in compile
    return compiler.compile(self, run_cfg)
  File "/home/sshresth/lava-nc/lava/src/lava/magma/compiler/compiler.py", line 998, in compile
    procs = self._find_processes(proc)
  File "/home/sshresth/lava-nc/lava/src/lava/magma/compiler/compiler.py", line 99, in _find_processes
    new_list.extend(self._find_processes(proc, seen_procs))
  File "/home/sshresth/lava-nc/lava/src/lava/magma/compiler/compiler.py", line 75, in _find_processes
    for in_port in proc.in_ports.members + proc.var_ports.members:
AttributeError: 'NoneType' object has no attribute 'in_ports'
```

**Comment by mathisrichter** [comment] 2022-02-04 18:35
This is because the virtual port object is interpreted as an `AbstractPort` object rather than a `AbstractVirtualPort` object in the compiler. The issue is fixed by switching out the order of inheritance of the concrete virtual port classes from
`class ReshapePort(AbstractPort, AbstractVirtualPort):`
to
`class ReshapePort(AbstractVirtualPort, AbstractPort):`

This is being addressed as part of the implementation of virtual ports.

**Closed** 2022-03-02 20:20 UTC
Labels: bug, compiler
