### ISSUE TITLE
When ProcessModel crashes via jupyter, parallel Python processes do not get cleaned up

### ISSUE THREAD

**Issue by awintel** [lava-nc/lava#88] opened 2021-11-22 03:37 UTC
During development code often crashes. When this happens in a parallel system Process (involving Python multiprocessing) via jupyter then there are a lot of parallel Python processes left that need to be killed manually.

Interestingly, this does not happen when running the same code from a *.py file (via PyCharm).

This needs to be investigated and fixed.

**Comment by ashishrao7** [comment] 2022-01-19 20:52
I can confirm that this definitely happens on a windows machine. I think there are stray python processes with low resource usage left behind on every kernel restart in a Jupyter notebook. The problem is more pressing when the process model hangs for various reasons. Usually it would hang because of a bug in the code. However, since Lava doesn't print out the error message that usually the library being used, e.g, numpy, would have printed out, the bug is not apparent. Under this circumstances a kernel restart would end leaving a huge chunk of memory being utilized for the stray lava process  from the previous kernel. While debugging lava code, this could very quickly fill up the memory (on multiple kernel restarts) and thus lead to seemingly random behavior (i.e. code that worked 5 minutes ago stops working) if the developer is not aware of this issue. 
The quick fix would be to open task manager and manually kill these stray processes. However, this affects productivity of the developer.

**Comment by joyeshmishra** [comment] 2023-01-18 23:59
Assigning to Mathis as this seems to be a generic bug. Please provide a way to replicate this and we can take a look if it is a runtime issue.

**Comment by tim-shea** [comment] 2024-01-17 18:35
This has mostly been fixed over time with better error handling, although it could still be improved further with a refactor of the multiprocessing implementation. That would be a separate, major task.

**Closed by tim-shea** 2024-01-17 18:35 UTC
Labels: 1-bug, 0-needs-review, area: magma/runtime
